export const SHOW_MODAL = "SHOW_MODAL";
export const VIEW_EMPLOYEE = "VIEW_EMPLOYEE";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const SELECT_EMPLOYEE = "SELECT_EMPLOYEE";
